definitions:
  AddImageResonse:
    properties:
      image_id:
        type: string
      image_url:
        type: string
    required:
    - image_id
    - image_url
    type: object
  CreatePostRequest:
    description: Request payload for creating a new post
    properties:
      content:
        type: string
      idempotency_key:
        type: string
      title:
        type: string
    required:
    - content
    - idempotency_key
    - title
    type: object
  CreatePostResponse:
    description: Response with ID of the created post
    properties:
      post_id:
        type: string
    type: object
  DeleteImageResonse:
    properties:
      image_id:
        type: string
    required:
    - image_id
    type: object
  EditPostRequest:
    description: Request payload for editing a post
    properties:
      content:
        type: string
      title:
        type: string
    required:
    - content
    - title
    type: object
  PostDetails:
    description: Response with updated post details
    properties:
      author_id:
        type: string
      content:
        type: string
      created_at:
        type: string
      indempotency_key:
        type: string
      post_id:
        type: string
      status:
        $ref: '#/definitions/TypePostStatus'
      title:
        type: string
      updated_at:
        type: string
    type: object
  PostResponse:
    properties:
      author:
        $ref: '#/definitions/UserResponse'
      content:
        type: string
      created_at:
        type: string
      images:
        items:
          $ref: '#/definitions/AddImageResonse'
        type: array
      post_id:
        type: string
      status:
        $ref: '#/definitions/TypePostStatus'
      title:
        type: string
      updated_at:
        type: string
    type: object
  TokenRefreshRequest:
    description: Request to refresh access token using refresh token
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  TokenRefreshResponse:
    description: Response with new access token
    properties:
      access_token:
        type: string
    type: object
  TypePostStatus:
    enum:
    - draft
    - published
    type: string
    x-enum-varnames:
    - DraftStatus
    - PublishedStatus
  TypeUserRole:
    enum:
    - author
    - reader
    type: string
    x-enum-varnames:
    - Author
    - Reader
  UpdatePostStatusRequest:
    description: Request to change post status (publish/unpublish)
    properties:
      status:
        allOf:
        - $ref: '#/definitions/TypePostStatus'
        enum:
        - published
        - draft
    required:
    - status
    type: object
  UserLoginRequest:
    description: Request payload for user authentication
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  UserLoginResponse:
    description: Response with authentication tokens after login
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user_id:
        type: string
    type: object
  UserRegistrationRequest:
    description: Request payload for registering a new user
    properties:
      email:
        type: string
      password:
        minLength: 8
        type: string
      role:
        allOf:
        - $ref: '#/definitions/TypeUserRole'
        enum:
        - reader
        - author
    required:
    - email
    - password
    - role
    type: object
  UserRegistrationResponse:
    description: Response with authentication tokens after registration
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user_id:
        type: string
    type: object
  UserResponse:
    properties:
      email:
        type: string
      user_id:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: Login data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/UserLoginResponse'
        "400":
          description: Incorrect body
        "403":
          description: Email or password incorrect
      summary: Login
      tags:
      - Auth
  /auth/refresh-token:
    post:
      consumes:
      - application/json
      description: Get access token by refresh token
      parameters:
      - description: Refresh token data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/TokenRefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/TokenRefreshResponse'
        "400":
          description: Incorrect body\nRefresh token expired or incorrect
      summary: Invoke refresh token
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Registrate a new user
      parameters:
      - description: Registration data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/UserRegistrationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/UserRegistrationResponse'
        "400":
          description: Incorrect email format\nIncorrect body
        "403":
          description: User alredy exsist
      summary: Registration
      tags:
      - Auth
  /post/{postId}:
    put:
      consumes:
      - application/json
      description: Edit post
      parameters:
      - description: Edit post data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/EditPostRequest'
      - description: Post ID
        format: uuid
        in: path
        name: postId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PostDetails'
        "400":
          description: Incorrect body\nRefresh token expired or incorrect
        "403":
          description: Access denied
        "404":
          description: Post not found
      security:
      - BearerAuth: []
      tags:
      - Poster
  /post/{postId}/images:
    post:
      consumes:
      - multipart/form-data
      description: Add Image
      parameters:
      - description: Post ID
        format: uuid
        in: path
        name: postId
        required: true
        type: string
      - description: Image
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/AddImageResonse'
        "400":
          description: Incorrect body\nRefresh token expired or incorrect
        "403":
          description: Access denied
        "404":
          description: Post not found
      security:
      - BearerAuth: []
      tags:
      - Poster
  /post/{postId}/images/{imageId}:
    delete:
      description: Add Image
      parameters:
      - description: Post ID
        format: uuid
        in: path
        name: postId
        required: true
        type: string
      - description: Image ID
        format: uuid
        in: path
        name: imageId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/DeleteImageResonse'
        "400":
          description: Incorrect body\nRefresh token expired or incorrect
        "403":
          description: Access denied
        "404":
          description: Post/Image not found
      security:
      - BearerAuth: []
      tags:
      - Poster
  /post/{postId}/status:
    patch:
      consumes:
      - application/json
      description: Publish post
      parameters:
      - description: Publish post data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/UpdatePostStatusRequest'
      - description: Post ID
        format: uuid
        in: path
        name: postId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/PostDetails'
        "400":
          description: Incorrect body\nRefresh token expired or incorrect
        "403":
          description: Access denied
        "404":
          description: Post not found
      security:
      - BearerAuth: []
      summary: Publicate post
      tags:
      - Poster
  /posts:
    get:
      consumes:
      - application/json
      description: Read all posts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/PostResponse'
            type: array
        "400":
          description: Incorrect body\nRefresh token expired or incorrect
        "403":
          description: Access denied
        "404":
          description: Post not found
      security:
      - BearerAuth: []
      summary: Read post
      tags:
      - Reader
    post:
      consumes:
      - application/json
      description: Create new post
      parameters:
      - description: Create post data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/CreatePostRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/CreatePostResponse'
        "400":
          description: Incorrect body
        "403":
          description: Incorrect user
        "409":
          description: Idempotency key already used
      security:
      - BearerAuth: []
      summary: Create post
      tags:
      - Poster
securityDefinitions:
  BearerAuth:
    description: 'Enter: Bearer {jwt_token}'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
